name: Refresh Instagram API Token

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  update_posts:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install
        shell: "bash"
        run: npm install

      - name: Refresh token and update secret
        env:
          IG_TOKEN: ${{ secrets.IG_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_PA_TOKEN }}
        shell: "bash"
        run: npm run refresh-ig-token
