name: Update Posts from Instagram

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update_posts:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install
        shell: "bash"
        run: npm install

      - name: Update
        env:
          IG_TOKEN: ${{ secrets.IG_TOKEN }}
        shell: "bash"
        run: npm run update-data

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore(automated): update posts from instagram"
          push: true

  call_deploy:
    uses: Notuom/poterie-par-kathy/.github/workflows/deploy.yml@main
